version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Dockerfileでファイルをコピーしているため、開発中のコード変更を反映するにはvolumesをマウントします。
    # 本番デプロイの場合はvolumesを削除し、COPYでイメージに焼き付けたコードを使用する方が一般的です。
    volumes:
      - .:/var/www/html 
    # ホストの8080ポートをコンテナの80ポートに、ホストの3306ポートをコンテナの3306ポートにマッピング
    ports:
      - "${PORT:-80}:80"
      #- "3306:3306" 
    environment:
      # DB_HOSTはlocalhostまたは127.0.0.1を設定
      - DB_HOST=127.0.0.1 
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-laraveluser}
      - DB_PASSWORD=${DB_PASSWORD:-laravelpass}
      - APP_KEY=${APP_KEY:-123456}
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}

# webサービスとdbサービスはDockerfile内で全て賄われるため削除

# volumesは不要（db_dataも不要）
# volumes:
#   db_data:
