name: Build and Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのソースコードをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Hubにログインする
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Dockerイメージをビルドして、Docker Hubにプッシュする
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/renderoutput_php_laravel:latest
